services:
  - type: web
    name: pared
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && npm install && npm run build:css && rm -rf node_modules && flask --app recipe_parser db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 application:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DATABASE_URL
        sync: false  # User must set this manually in Render dashboard
